### ISSUE TITLE
Error during package installation

### ISSUE THREAD

**Issue by ProfiSketch** [Claus1/unigui#2] opened 2022-09-11 08:55 UTC
D:\REPS\Sandbox\UniGui\unigui> pip install unigui 
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
Collecting unigui
  Using cached unigui-1.1.11.tar.gz (731 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-hgpdw39v\unigui_ca9e19526fd14c458830cf9006f9b96b\setup.py", line 10, in <module>
          long_description=open('README.md').read(),
        File "C:\Python310\lib\encodings\cp1251.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 3234: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\python310\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\python310\lib\site-packages)

**Comment by Claus1** [comment] 2022-09-12 08:19
The issue is not relevant to the library and is caused by broken python installation. Check or use the library on the other OS or python installation.

**Comment by Claus1** [comment] 2022-09-27 21:45
Closed as irrelevant.

**Closed by Claus1** 2022-09-27 21:45 UTC
